version: '3'
services:
  node_alice:
    image: dfinn-node
    container_name: alice
    command: >
      /Dfinn/target/release/dfinn-node --base-path /tmp/alice --chain local --alice --port 30333 --ws-port 9945 --rpc-port 9933 --node-key 0000000000000000000000000000000000000000000000000000000000000001 --telemetry-url "wss://telemetry.polkadot.io/submit/ 0" --validator
    ports:
      - "30333:30333"
      - "9933:9933"
      - "9945:9944"
    volumes:
      - "polkadot-data-alice:/data"
    networks:
      testing_net:
        ipv4_address: 172.28.1.1

  node_bob:
    image: dfinn-node
    container_name: bob
    command: >
    ports:
      - "30334:30333"
      - "9934:9933"
      - "9946:9944"
    volumes:
      - "polkadot-data-bob:/data"
    links:
      - "node_alice:alice"
    networks:
      testing_net:
        ipv4_address: 172.28.1.2

volumes:
  polkadot-data-alice:
  polkadot-data-bob:

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
