[profile.release]
panic = 'unwind'

[workspace]
members = [
    'node',
    'pallets/ocex',
    'pallets/pdex-migration',
    'runtime',
    'contracts/uniswap_v2',
]


#[patch."https://github.com/open-web3-stack/open-runtime-module-library.git"]
[patch."https://github.com/open-web3-stack/open-runtime-module-library.git"]
orml-vesting = { git = "https://github.com/Gauthamastro/open-runtime-module-library.git",  branch="gj-substrate-master"}