version: "3.2"
services:
  bootnode-alice:
    hostname: bootnode-alice
    build:
      context: ./bootnode
    ports:
      - 30333:30333
    networks:
      chainnet:
        ipv4_address: 172.25.0.101 # Bootnode IP

  validator-bob:
    hostname: validator-bob
    depends_on:
      - bootnode-alice
    build:
      context: .
    container_name: validator-bob
    environment:
      - bootnodePeerId=12D3KooWG7MkQkrRqikjtKq4ToUqJDnmVGsghJU8ACvUJqWjKAVW
      - bootnodeIP=172.25.0.101
      - validator=bob
    ports:
      - 30334:30333
#    volumes:
#      - eth-data-1:/root/.ethash
    networks:
      chainnet:
        ipv4_address: 172.25.0.102 # The monitor needs to know this address

  validator-charlie:
    hostname: validator-charlie
    depends_on:
      - bootnode-alice
    container_name: validator-charlie
    build:
      context: .
    environment:
      - bootnodePeerId=12D3KooWG7MkQkrRqikjtKq4ToUqJDnmVGsghJU8ACvUJqWjKAVW
      - bootnodeIP=172.25.0.101
      - validator=charlie
    ports:
      - 30335:30333
#    volumes:
#      - eth-data-2:/root/.ethash
    networks:
      chainnet:
        ipv4_address: 172.25.0.103

networks:
  chainnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/24

#volumes:
#  eth-data-1:
#  eth-data-2:
#  eth-data-3: