- hosts: thea_node
#  serial: 1
  become: yes
  order: sorted
  vars:
    bootnode_ip: "3.6.116.184"
    bootnode_peer_id: "12D3KooWJV4JKrVfoNue5MXfuZAXi9xou7xvyBkS6MuvfwqiJbes"
    bootnodes: "/ip4/{{ bootnode_ip }}/tcp/30333/p2p/{{ bootnode_peer_id }}"

  tasks:
    - name: Basic preparation
      import_tasks: base.yml

    - name: Set hostname
      hostname:
        name: "{{ inventory_hostname }}"

    - name: Download polkadex-thea-node chainspec
      get_url:
        url: https://polkadex-thea.s3.ap-south-1.amazonaws.com/customSpecRaw.json
        dest: /etc/customSpecRaw.json

    - name: Download polkadex-thea-node
      get_url:
        url: https://polkadex-thea.s3.ap-south-1.amazonaws.com/polkadex-thea-node
        dest: /usr/local/bin/polkadex-thea-node
        mode: "0755"

    - name: Create service file
      template:
        src: templates/node.j2
        dest: /etc/systemd/system/polkadex-thea-node.service
        owner: root
        group: root
        mode: 0644
      notify: Restart polkadex-thea-node

    - name: Make sure service is running
      systemd:
        name: polkadex-thea-node
        state: started
        enabled: yes

    - name: Pause for 60 seconds
      pause:
        seconds: 60

  handlers:
    - name: Restart polkadex-thea-node
      systemd:
        name: polkadex-thea-node
        state: restarted
        daemon_reload: yes
