[package]
authors = ['Polkadex Authors']
description = 'Polkapool, pallet for governance based feeless swaps'
edition = '2018'
homepage = 'https://polkadex.trade'
name = 'pallet-polkapool'
version = '0.1.0'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
# Polkadex Primitives
polkadex-primitives = { git = "https://github.com/Polkadex-Substrate/polkadex-primitives", branch = "substrate-monthly-2021-09+1", default-features=false}

# # ORML
orml-currencies = { git = "https://github.com/Gauthamastro/open-runtime-module-library.git",  branch="gj-substrate-master", default-features = false }
orml-traits = { git = "https://github.com/Gauthamastro/open-runtime-module-library.git",  branch="gj-substrate-master", default-features = false }

# external dependencies
codec = {default-features = false, features = ['derive'], package = 'parity-scale-codec', version = '2.0.0'}
rand = {default-features = false, version = '0.8.0'}
rand_chacha = {default-features = false, version = '0.3.0'}
# Substrate dependencies
frame-benchmarking = {default-features = false, optional = true, tag = "monthly-2021-09+1", version = "4.0.0-dev", git = 'https://github.com/paritytech/substrate'}
frame-support = {default-features = false, tag = "monthly-2021-09+1", version = "4.0.0-dev", git = 'https://github.com/paritytech/substrate'}
frame-system = {default-features = false, tag = "monthly-2021-09+1", version = "4.0.0-dev", git = 'https://github.com/paritytech/substrate'}
sp-arithmetic = {default-features = false, tag = "monthly-2021-09+1", version = "4.0.0-dev", git = 'https://github.com/paritytech/substrate'}
sp-core = {default-features = false, tag = "monthly-2021-09+1", version = "4.0.0-dev", git = 'https://github.com/paritytech/substrate'}
sp-std = {default-features = false, tag = "monthly-2021-09+1", version = "4.0.0-dev", git = 'https://github.com/paritytech/substrate'}
pallet-babe = { default-features = false, tag = "monthly-2021-09+1", version = "4.0.0-dev", git = "https://github.com/paritytech/substrate" }
sp-consensus-vrf = { default-features = false, tag = "monthly-2021-09+1", version = "0.10.0-dev", git = "https://github.com/paritytech/substrate" }
sp-runtime = {default-features = false, tag = "monthly-2021-09+1", version = "4.0.0-dev", git = 'https://github.com/paritytech/substrate'}

[dev-dependencies]
serde = '1.0.119'
sp-io = {default-features = false, tag = "monthly-2021-09+1", version = "4.0.0-dev", git = 'https://github.com/paritytech/substrate'}

[features]
default = ['std']
# runtime-benchmarks = ['frame-benchmarking']
std = [
	"rand/std",
	"rand_chacha/std",
	'codec/std',
	'frame-support/std',
	'frame-system/std',
	'frame-benchmarking/std',
	'orml-currencies/std',
	'orml-traits/std',
	"sp-consensus-vrf/std",
	'polkadex-primitives/std',
	'sp-arithmetic/std',
	'sp-core/std',
	'sp-std/std',
	'pallet-babe/std',
]
try-runtime = ['frame-support/try-runtime']
